version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
  nginx:
    image: nginx
    ports:
      - "8080:80"
#    volumes:
#      - ./templates:/etc/nginx/templates

